// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBy8UwRnMKJ_ZgSVE450qigHLRbCwbF9wA',
    appId: '1:788358162557:web:17b1cba9107e4e588b6914',
    messagingSenderId: '788358162557',
    projectId: 'sohib-abdimannabov-dream',
    authDomain: 'sohib-abdimannabov-dream.firebaseapp.com',
    storageBucket: 'sohib-abdimannabov-dream.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEPMt0oJhwQiEIvTJO5ybs3ZD1EHhyiYE',
    appId: '1:788358162557:android:461243a7136e48c08b6914',
    messagingSenderId: '788358162557',
    projectId: 'sohib-abdimannabov-dream',
    storageBucket: 'sohib-abdimannabov-dream.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBost4AAz55ZXhAYvfLQUNtKIgNUeDdqFQ',
    appId: '1:788358162557:ios:a24b9f2605c810e28b6914',
    messagingSenderId: '788358162557',
    projectId: 'sohib-abdimannabov-dream',
    storageBucket: 'sohib-abdimannabov-dream.firebasestorage.app',
    iosBundleId: 'com.example.clipReact',
  );
}
